;########### APP ####################
[General]
EnableLogs=true
LogPath=C:\Logs\ExampleApp

;########### INSTRUMENTS ####################

[DAQ]
Host = 192.168.4.1
Port = 502
TimeoutMs = 5000


[Coils]
StartAddress = 0
Count = 4

[Monitor]
IntervalMs = 500
MaxRetries = 3
RetryDelayMs = 2000

[Database]
Host = 192.168.1.150

[DMM]
Port=COM3
Bauds=115200

[Vision_camera]
Host=192.168.1.1
Port=8500

;########### TEST 1 ####################

[DC_Voltage_Test]
upper_limit=7.4
lower_limit=5.0	

;########### TEST 2 ####################

[Vision_LED_test_program]
program=001