<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppSettings.json" />
    <None Remove="config.ini" />
    <None Remove="Resources\Images\add.png" />
    <None Remove="Resources\Images\arrow.png" />
    <None Remove="Resources\Images\attach.png" />
    <None Remove="Resources\Images\bookmark.png" />
    <None Remove="Resources\Images\cerrar.png" />
    <None Remove="Resources\Images\cerrar2.png" />
    <None Remove="Resources\Images\check.png" />
    <None Remove="Resources\Images\circuito.png" />
    <None Remove="Resources\Images\clock.png" />
    <None Remove="Resources\Images\close.png" />
    <None Remove="Resources\Images\codigo-qr.png" />
    <None Remove="Resources\Images\cogwheel.png" />
    <None Remove="Resources\Images\correcto.png" />
    <None Remove="Resources\Images\database.png" />
    <None Remove="Resources\Images\diskette.png" />
    <None Remove="Resources\Images\Edge.png" />
    <None Remove="Resources\Images\edit.png" />
    <None Remove="Resources\Images\enter.png" />
    <None Remove="Resources\Images\focus.png" />
    <None Remove="Resources\Images\folder.png" />
    <None Remove="Resources\Images\funnel.png" />
    <None Remove="Resources\Images\home.png" />
    <None Remove="Resources\Images\inicialize_app_icons.png" />
    <None Remove="Resources\Images\lanzadera.png" />
    <None Remove="Resources\Images\lcd.png" />
    <None Remove="Resources\Images\local-area-network.png" />
    <None Remove="Resources\Images\logo-smitech.png" />
    <None Remove="Resources\Images\logout.png" />
    <None Remove="Resources\Images\maximize.png" />
    <None Remove="Resources\Images\microchip.png" />
    <None Remove="Resources\Images\minimize.png" />
    <None Remove="Resources\Images\multimetro.png" />
    <None Remove="Resources\Images\nidec-icon.jpeg" />
    <None Remove="Resources\Images\nidec-logo-black-white-no-background.png" />
    <None Remove="Resources\Images\nidec-logo-black_and_white.png" />
    <None Remove="Resources\Images\Nidec_logo_green.png" />
    <None Remove="Resources\Images\smitech-logo-no-background.png" />
    <None Remove="Resources\Images\undo.png" />
    <None Remove="Resources\Images\usb.png" />
    <None Remove="Resources\Images\vectorseek.com-Nidec Logo Vector.png" />
    <None Remove="Resources\Images\webcam.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AppSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="config.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Config__ni_lib\Config__ni_lib\ConfigIniLib.csproj" />
    <ProjectReference Include="..\..\ModbusTcpLib\ModbusTcpLib\ModbusTcpLib.csproj" />
    <ProjectReference Include="..\..\SqlUtilityLibrary\SqlUtilityLibrary\SqlUtilityLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\add.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\arrow.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\attach.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\bookmark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\cerrar.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\cerrar2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\check.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\circuito.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\clock.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\codigo-qr.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\cogwheel.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\correcto.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\database.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\diskette.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Edge.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\edit.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\enter.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\focus.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\funnel.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\home.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\inicialize_app_icons.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\lanzadera.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\lcd.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\local-area-network.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\logo-smitech.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\logout.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\close.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\folder.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\maximize.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\microchip.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\minimize.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\multimetro.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\nidec-icon.jpeg" />
    <Resource Include="Resources\Images\nidec-logo-black-white-no-background.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\nidec-logo-black_and_white.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Nidec_logo_green.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\smitech-logo-no-background.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\undo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\usb.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\vectorseek.com-Nidec Logo Vector.png" />
    <Resource Include="Resources\Images\webcam.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\CoilsIndicator.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\InicializeScreen.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Navigation\Extensions\" />
  </ItemGroup>

</Project>
